### 전 계좌 조회

In [26]:
from urllib.request import urlopen
from urllib.parse import urlencode, unquote, quote_plus
import requests, json
import pandas as pd

def callAPI01():
    # 데이터를 받고자하는 사이트의 포멧에 맞게 url을 수정하고 보내는 코드
    url01 = 'https://openapi.wooribank.com:444/oai/wb/v1/finance/getIndivAllAccInfo?'
    values01  = {
      "dataHeader": {
        "UTZPE_CNCT_IPAD": "",
        "UTZPE_CNCT_MCHR_UNQ_ID": "",
        "UTZPE_CNCT_TEL_NO_TXT": "",
        "UTZPE_CNCT_MCHR_IDF_SRNO": "",
        "UTZ_MCHR_OS_DSCD": "",
        "UTZ_MCHR_OS_VER_NM": "",
        "UTZ_MCHR_MDL_NM": "",
        "UTZ_MCHR_APP_VER_NM": ""
      },
      "dataBody": {}
    }
    headers01 = {  'appkey':'l7xxyuXx5JXUfAkmjfHJ8lZEKWn9QbsNzbal',  'Content-Type':'application/json; charset=utf-8' }
    post_data01 = requests.post(url01, json = values01, headers = headers01)
    result_data01 = post_data01.json()
    items01 = result_data01['dataBody']['GRID']
    AllAcc =pd.DataFrame(items01)
    return AllAcc['PBOK_BAL'].astype('float').sum()

In [51]:
callAPI01()

72525150.0

In [18]:
type(AllAcc['PBOK_BAL'][0])

str

### 계좌 기본 조회

In [3]:
url02 = 'https://openapi.wooribank.com:444/oai/wb/v1/finance/getAccBasicInfo?'
values02  = {
  "dataHeader": {
    "UTZPE_CNCT_IPAD": "",
    "UTZPE_CNCT_MCHR_UNQ_ID": "",
    "UTZPE_CNCT_TEL_NO_TXT": "",
    "UTZPE_CNCT_MCHR_IDF_SRNO": "",
    "UTZ_MCHR_OS_DSCD": "",
    "UTZ_MCHR_OS_VER_NM": "",
    "UTZ_MCHR_MDL_NM": "",
    "UTZ_MCHR_APP_VER_NM": ""
  },
  "dataBody": {
    "INQ_ACNO": "1002123456789",
    "INQ_BAS_DT": "20210220",
    "ACCT_KND": "P",
    "INQ_CUCD": "KRW"
  }
}
headers02 = {  'appkey':'l7xxyuXx5JXUfAkmjfHJ8lZEKWn9QbsNzbal',  'Content-Type':'application/json; charset=utf-8' }
post_data02 = requests.post(url02, json = values02, headers = headers02)
result_data02 = post_data02.json()
#print(result_data)
items02 = result_data02['dataBody']
AccBasic =pd.DataFrame.from_records([items02])
AccBasic

,ACNO,DPS_STCD,CUCD,CT_BAL,PAY_AVL_AM,NEW_DT,XPR_DT,TXTR_PDCD,MM_PID_AM,FDN_DSCD,TDY_EVL_AM,IVST_PRN,SMPL_PRFT_RT,LST_LN_PCS_AM
0,10062776*****,01,KRW,1215030.000,2115030.000,2020-11-02,2021-11-02,,3320000.000,00,0,0,,

In [13]:
url03 = 'https://openapi.wooribank.com:444/oai/wb/v1/finance/getAccTransList?'
values03  = {
  "dataHeader": {
    "UTZPE_CNCT_IPAD": "",
    "UTZPE_CNCT_MCHR_UNQ_ID": "",
    "UTZPE_CNCT_TEL_NO_TXT": "",
    "UTZPE_CNCT_MCHR_IDF_SRNO": "",
    "UTZ_MCHR_OS_DSCD": "",
    "UTZ_MCHR_OS_VER_NM": "",
    "UTZ_MCHR_MDL_NM": "",
    "UTZ_MCHR_APP_VER_NM": ""
  },
  "dataBody": {
    "INQ_ACNO": "1002123456789",
    "INQ_STA_DT": "20210101",
    "INQ_END_DT": "20210310",
    "NEW_DT": "20140522",
    "ACCT_KND": "P",
    "CUCD": "KRW"
  }
}
headers03 = {  'appkey':'l7xxyuXx5JXUfAkmjfHJ8lZEKWn9QbsNzbal',  'Content-Type':'application/json; charset=utf-8' }
post_data03 = requests.post(url03, json = values03, headers = headers03)
result_data03 = post_data03.json()
#print(result_data)
items03 = result_data03['dataBody']['GRID']
AccTrans =pd.DataFrame(items03)
AccTrans

,TRN_DT,TRN_TM,TRN_SRNO,CUCD,PBOK_PRNG_OTLN_CD,DPS_RAP_KDCD,MD_KDCD,RCV_AM,PAY_AM,DPS_BAL,TRN_TXT,PID_SQ,TRN_STCD
0,2021-04-28,121322,4,KRW,0318,200,MIBMPSB2,0.000,550000.000,371900000.000,홍길동,0,282500000.000
1,2021-04-24,081050,2,KRW,0318,200,MIBMPSB2,679000.000,0.000,803700000.000,카드취소,0,476700000.000
2,2021-04-01,174257,5,KRW,0318,100,MIBMPSB2,0.000,151000.000,789600000.000,월급여,0,426000000.000

In [65]:
def callAPI04():
    url04 = 'https://openapi.wooribank.com:444/oai/wb/v1/credit/getCreditLoanEmFnd?'
    values04  = {
      "dataHeader": {
        "UTZPE_CNCT_IPAD": "",
        "UTZPE_CNCT_MCHR_UNQ_ID": "",
        "UTZPE_CNCT_TEL_NO_TXT": "",
        "UTZPE_CNCT_MCHR_IDF_SRNO": "",
        "UTZ_MCHR_OS_DSCD": "",
        "UTZ_MCHR_OS_VER_NM": "",
        "UTZ_MCHR_MDL_NM": "",
        "UTZ_MCHR_APP_VER_NM": ""
      },
      "dataBody": {
        "ENCY_ACNM_NO": "11111111111111111111",
        "CUS_KORL_NM": "홍길동",
        "RQ_AM": "30000000"
      }
    }
    headers04 = {  'appkey':'l7xxyuXx5JXUfAkmjfHJ8lZEKWn9QbsNzbal',  'Content-Type':'application/json; charset=utf-8' }
    post_data04 = requests.post(url04, json = values04, headers = headers04)
    result_data04 = post_data04.json()
    #print(result_data)
    items04 = result_data04['dataBody']
    CreditLimit =pd.DataFrame.from_records([items04])
    return list(CreditLimit['APV_AM'])

In [66]:
callAPI04()

[3000000.0]

In [67]:
def callAPI05():
    url05 = 'https://openapi.wooribank.com:444/oai/wb/v1/credit/getCreditLoanWon?'
    values05  = {
      "dataHeader": {
        "UTZPE_CNCT_IPAD": "",
        "UTZPE_CNCT_MCHR_UNQ_ID": "",
        "UTZPE_CNCT_TEL_NO_TXT": "",
        "UTZPE_CNCT_MCHR_IDF_SRNO": "",
        "UTZ_MCHR_OS_DSCD": "",
        "UTZ_MCHR_OS_VER_NM": "",
        "UTZ_MCHR_MDL_NM": "",
        "UTZ_MCHR_APP_VER_NM": ""
      },
      "dataBody": {
        "ENCY_ACNM_NO": "1111111111111",
        "CUS_KORL_NM": "홍길동",
        "RQ_AM": "10000000",
        "BZPE_CRNO": "1002030000",
        "ENCN_DT": "1",
        "HLD_YINC_AM": "1",
        "ORG_NAME": "1",
        "EXTR_IDF_REFC_KEY_TXT": "woori202101011234567"
      }
    }
    headers05 = {  'appkey':'l7xxyuXx5JXUfAkmjfHJ8lZEKWn9QbsNzbal',  'Content-Type':'application/json; charset=utf-8' }
    post_data05 = requests.post(url05, json = values05, headers = headers05)
    result_data05 = post_data05.json()
    #print(result_data)
    items05 = result_data05['dataBody']
    WonLimit = pd.DataFrame.from_records([items05])
    return list(WonLimit['APV_AM'])

In [68]:
def callAPI06():
    url06 = 'https://openapi.wooribank.com:444/oai/wb/v1/newcar/getNewCarLoanAm?'
    values06  = {
      "dataHeader": {
        "UTZPE_CNCT_IPAD": "",
        "UTZPE_CNCT_MCHR_UNQ_ID": "",
        "UTZPE_CNCT_TEL_NO_TXT": "",
        "UTZPE_CNCT_MCHR_IDF_SRNO": "",
        "UTZ_MCHR_OS_DSCD": "",
        "UTZ_MCHR_OS_VER_NM": "",
        "UTZ_MCHR_MDL_NM": "",
        "UTZ_MCHR_APP_VER_NM": ""
      },
      "dataBody": {
        "DBPE_ANL_ICM_AM": "15000000",
        "GRN_NCAR_YN": "Y",
        "CAR_PR": "30000000",
        "CRINF_INQ_AGR_YN": "Y",
        "INF_OFR_MND_AGR_YN": "Y",
        "GAT_UTZ_MND_AGR_YN": "Y",
        "CUS_IDF_INF_AGR_YN": "Y",
        "INF_OFR_CHC_AGR_YN": "Y",
        "GAT_UTZ_CHC_AGR_YN": "Y"
      }
    }
    headers06 = {  'appkey':'l7xxyuXx5JXUfAkmjfHJ8lZEKWn9QbsNzbal',  'Content-Type':'application/json; charset=utf-8' }
    post_data06 = requests.post(url06, json = values06, headers = headers06)
    result_data06 = post_data06.json()
    #print(result_data)
    items06 = result_data06['dataBody']
    NewCar =pd.DataFrame.from_records([items06])
    return list(NewCar['LN_AVL_AM'])

In [69]:
def callAPI07():
    url07 = 'https://openapi.wooribank.com:444/oai/wb/v1/lease/getLeaseHouseLoanAm?'
    values07  = {
      "dataHeader": {
        "UTZPE_CNCT_IPAD": "",
        "UTZPE_CNCT_MCHR_UNQ_ID": "",
        "UTZPE_CNCT_TEL_NO_TXT": "",
        "UTZPE_CNCT_MCHR_IDF_SRNO": "",
        "UTZ_MCHR_OS_DSCD": "",
        "UTZ_MCHR_OS_VER_NM": "",
        "UTZ_MCHR_MDL_NM": "",
        "UTZ_MCHR_APP_VER_NM": ""
      },
      "dataBody": {
        "CRINF_INQ_AGR_YN": "Y",
        "PSN_INF_OFR_AGR_YN": "Y",
        "PRCI_UTZ_AGR_YN": "Y",
        "SLF_ANL_ICM_AM": "67000000",
        "ADR_KDCD": "3",
        "POST_SRNO": "0",
        "BLD_MNG_NO": "1111111111",
        "MDBT_RQ_AM": "0",
        "LEAS_GRN_AM": "70000000",
        "LAWC_ADDN_NO": ""
      }
    }
    headers07 = {  'appkey':'l7xxyuXx5JXUfAkmjfHJ8lZEKWn9QbsNzbal',  'Content-Type':'application/json; charset=utf-8' }
    post_data07 = requests.post(url07, json = values07, headers = headers07)
    result_data07 = post_data07.json()
    #print(result_data)
    items07 = result_data07['dataBody']
    HouseLoan =pd.DataFrame.from_records([items07])
    return list(HouseLoan['FRCS_AVL_LN_AM'])

In [70]:
def callAPI08():
    url08 = 'https://openapi.wooribank.com:444/oai/wb/v1/apt/getAptLoanAm?'
    values08  = {
      "dataHeader": {
        "UTZPE_CNCT_IPAD": "",
        "UTZPE_CNCT_MCHR_UNQ_ID": "",
        "UTZPE_CNCT_TEL_NO_TXT": "",
        "UTZPE_CNCT_MCHR_IDF_SRNO": "",
        "UTZ_MCHR_OS_DSCD": "",
        "UTZ_MCHR_OS_VER_NM": "",
        "UTZ_MCHR_MDL_NM": "",
        "UTZ_MCHR_APP_VER_NM": ""
      },
      "dataBody": {
        "TRN_KD_DIS": "01",
        "APT_DJ_CD": "11111111",
        "PYT": "34",
        "PYT_TYP_TXT": "A",
        "MKPR_BAS_DT": "20200314",
        "GEN_TRN_AM": "780000000",
        "SB_ULPR": "820000000",
        "SB_LLPR": "750000000",
        "RNT_ULPR": "0",
        "RNT_LLPR": "0",
        "SIDO_CD": "01",
        "ACDS_CD": "010",
        "DNEM_CD": "050",
        "LI_CD": "01",
        "BLD_NM": "ooo 아파트",
        "DONG_ADR": "서울시 동대문구 장안0동 ",
        "HO_ADR": "A동 000호",
        "ALL_FCNT": "25",
        "EQV_FCNT": "12",
        "TOT_HHLD_CN": "644",
        "SQM": "108",
        "ALL_ROOM_NCNT": "",
        "RNT_ROOM_NCNT": "0",
        "LTHR_AM": "0",
        "PRK_AM": "0",
        "LN_MECN": "48",
        "CNAD_TEL_NO_1": "01012345678",
        "CNAD_TEL_NO_2": "",
        "CNAD_TEL_NO_3": "",
        "RQPE_ITCSNO": "1111111111111",
        "RQPE_FNM": "홍길동",
        "INET_CNSL_TRN_DSCD": "1",
        "APT_EVL_ISCD": "3",
        "MKPR_DSCD": "1",
        "LN_HOPE_BRCD": "111111",
        "LN_RQ_AM": "200000000",
        "ADVPE_ENO": "11111111",
        "FD_USCD": "2",
        "LN_HOPE_DT": "20210214",
        "BZBR_COLPE_ALOC_YN": "Y"
      }
    }
    headers08 = {  'appkey':'l7xxyuXx5JXUfAkmjfHJ8lZEKWn9QbsNzbal',  'Content-Type':'application/json; charset=utf-8' }
    post_data08 = requests.post(url08, json = values08, headers = headers08)
    result_data08 = post_data08.json()
    #print(result_data)
    items08 = result_data08['dataBody']
    AptLoan =pd.DataFrame.from_records([items08])
    return list(AptLoan['LN_AVL_AM'])

### 필요한 데이터 뽑아내기

In [20]:
FinancialData = pd.DataFrame({'Total Assets': AllAcc['PBOK_BAL'].astype('float').sum(),
                              '신용 대출 한도' : CreditLimit['APV_AM'],
                              '직장인 대출 한도' : WonLimit['APV_AM'],
                              '신차 대출 한도' : NewCar['LN_AVL_AM'],
                              '전세 자금 대출 한도' : HouseLoan['FRCS_AVL_LN_AM'],
                              '아파트 담보 대출 한도' : AptLoan['LN_AVL_AM']
                             })

FinancialData

   Total Assets   신용 대출 한도   직장인 대출 한도  신차 대출 한도 전세 자금 대출 한도 아파트 담보 대출 한도
0    66865150.0  3000000.0  76900000.0  02100000    16500000     38500000

In [74]:
FinancialData = pd.DataFrame(columns=['Total Assets', '신용 대출 한도', '직장인 대출 한도', 
                                      '신차 대출 한도', '전세 자금 대출 한도', '아파트 담보 대출 한도' ])

In [75]:
for idx in range(10):
    # DataFrame에 특정 정보를 이용하여 data 채우기
    FinancialData = FinancialData.append(pd.DataFrame([[idx, callAPI01(), callAPI04(),callAPI05(),callAPI06(), callAPI07(),callAPI08()]], 
                                                      columns=['idx','Total Assets', '신용 대출 한도', '직장인 대출 한도','신차 대출 한도', '전세 자금 대출 한도', '아파트 담보 대출 한도' ]), ignore_index=True)
FinancialData.set_index('idx', inplace=True)

In [78]:
FinancialData

,Total Assets,신용 대출 한도,직장인 대출 한도,신차 대출 한도,전세 자금 대출 한도,아파트 담보 대출 한도
idx,,,,,,
0.0,27125150.0,[3000000.0],[10700000.0],[56300000],[31500000],[84500000]
1.0,22995150.0,[3000000.0],[47400000.0],[63900000],[12500000],[08500000]
2.0,90815150.0,[3000000.0],[37100000.0],[52900000],[40500000],[86500000]
3.0,83355150.0,[3000000.0],[46600000.0],[63100000],[46500000],[32500000]
4.0,31565150.0,[3000000.0],[12200000.0],[88400000],[77500000],[25500000]
5.0,83565150.0,[3000000.0],[55000000.0],[84100000],[70500000],[90500000]
6.0,118225150.0,[3000000.0],[96200000.0],[17800000],[40500000],[79500000]
7.0,112145150.0,[3000000.0],[67700000.0],[45800000],[33500000],[60500000]
8.0,48565150.0,[3000000.0],[75400000.0],[65800000],[35500000],[14500000]
9.0,90215150.0,[3000000.0],[53800000.0],[24500000],[14500000],[59500000]

In [ ]:
FinancialData.set_index('idx', inplace=True, dtype=int )

In [ ]:
def call_API(start_date, end_date):
    dt = pd.date_range(start_date, end_date)

  
    headers = {  'appkey':'l7xxyuXx5JXUfAkmjfHJ8lZEKWn9QbsNzbal',  'Content-Type':'application/json; charset=utf-8' }
    for i in range(8):
        url = 'https://openapi.wooribank.com:444/oai/wb/v1/'
        #URL = url.format(authkey=key, searchdate=date)
        response = requests.get(URL, headers=headers, verify=False)
        df = pd.DataFrame(response.json())
        result = pd.concat([df], keys=[date])
        print(result)
        #result.to_csv("C:/Users/digus/Anaconda3/exchangeRate/exchange_%s.csv" % date, encoding="EUC-KR")
    return result